#include "includes/map.h"

void IntArrayToSpriteMap(GameMap * map, int array[MAP_HEIGHT][MAP_WIDTH]) {
	Texture2D textures[] = {
		{0},
		LoadTexture("assets/Tiles/Default/Floor.png"),
		LoadTexture("assets/Tiles/Default/Wall.png"),
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		LoadTexture("assets/Tiles/Light/image_part_001.png"),
		LoadTexture("assets/Tiles/Light/image_part_002.png"),
		LoadTexture("assets/Tiles/Light/image_part_003.png"),
		LoadTexture("assets/Tiles/Light/image_part_004.png"),
		LoadTexture("assets/Tiles/Light/image_part_004.png"),
		LoadTexture("assets/Tiles/Bench/image_part_001.png"),
		LoadTexture("assets/Tiles/Bench/image_part_002.png"),
		LoadTexture("assets/Tiles/Bench/image_part_003.png"),
		LoadTexture("assets/Tiles/Bench/image_part_004.png"),
		LoadTexture("assets/Tiles/Bed/image_part_001.png"),
		LoadTexture("assets/Tiles/Bed/image_part_002.png"),
		LoadTexture("assets/Tiles/Bed/image_part_003.png"),
		LoadTexture("assets/Tiles/Bed/image_part_004.png"),
		LoadTexture("assets/Tiles/Bed/image_part_005.png"),
		LoadTexture("assets/Tiles/Bed/image_part_006.png"),
		LoadTexture("assets/Tiles/Bed/image_part_007.png"),
		LoadTexture("assets/Tiles/Bed/image_part_008.png"),
		LoadTexture("assets/Tiles/Long desk/image_part_001.png"),
		LoadTexture("assets/Tiles/Long desk/image_part_002.png"),
		LoadTexture("assets/Tiles/Long desk/image_part_003.png"),
		LoadTexture("assets/Tiles/Long desk/image_part_004.png"),
		LoadTexture("assets/Tiles/Long desk/image_part_005.png"),
		LoadTexture("assets/Tiles/Long desk/image_part_006.png"),
		LoadTexture("assets/Tiles/Long desk/image_part_007.png"),
		LoadTexture("assets/Tiles/Long desk/image_part_008.png"),
		{0},
		{0},
		{0},
		{0},
		LoadTexture("assets/Tiles/Wardrobe/image_part_001.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_002.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_003.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_004.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_005.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_006.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_007.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_008.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_009.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_010.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_011.png"),
		LoadTexture("assets/Tiles/Wardrobe/image_part_012.png"),
		{0},
		{0},
		{0},
		{0},
		LoadTexture("assets/Tiles/Long cabinet/image_part_001.png"),
		LoadTexture("assets/Tiles/Long cabinet/image_part_002.png"),
		LoadTexture("assets/Tiles/Long cabinet/image_part_003.png"),
		LoadTexture("assets/Tiles/Long cabinet/image_part_004.png"),
		LoadTexture("assets/Tiles/Long cabinet/image_part_005.png"),
		LoadTexture("assets/Tiles/Long cabinet/image_part_006.png"),
		LoadTexture("assets/Tiles/Long cabinet/image_part_007.png"),
		LoadTexture("assets/Tiles/Long cabinet/image_part_008.png"),
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		{0},
		LoadTexture("assets/Tiles/Engine/image_part_001.png"),
		LoadTexture("assets/Tiles/Engine/image_part_002.png"),
		LoadTexture("assets/Tiles/Engine/image_part_003.png"),
		LoadTexture("assets/Tiles/Engine/image_part_004.png"),
		LoadTexture("assets/Tiles/Engine/image_part_005.png"),
		LoadTexture("assets/Tiles/Engine/image_part_006.png"),
		LoadTexture("assets/Tiles/Engine/image_part_007.png"),
		LoadTexture("assets/Tiles/Engine/image_part_008.png"),
		LoadTexture("assets/Tiles/Engine/image_part_009.png"),
		LoadTexture("assets/Tiles/Engine/image_part_010.png"),
		LoadTexture("assets/Tiles/Engine/image_part_011.png"),
		LoadTexture("assets/Tiles/Engine/image_part_012.png"),
		LoadTexture("assets/Tiles/Engine/image_part_013.png"),
		LoadTexture("assets/Tiles/Engine/image_part_014.png"),
		LoadTexture("assets/Tiles/Engine/image_part_015.png"),
		LoadTexture("assets/Tiles/Engine/image_part_016.png"),
		LoadTexture("assets/Tiles/Engine/image_part_017.png"),
		LoadTexture("assets/Tiles/Engine/image_part_018.png"),
		LoadTexture("assets/Tiles/Engine/image_part_019.png"),
		LoadTexture("assets/Tiles/Engine/image_part_020.png"),
		LoadTexture("assets/Tiles/Engine/image_part_021.png"),
		LoadTexture("assets/Tiles/Engine/image_part_022.png"),
		LoadTexture("assets/Tiles/Engine/image_part_023.png"),
		LoadTexture("assets/Tiles/Engine/image_part_024.png"),
		LoadTexture("assets/Tiles/Engine/image_part_025.png"),
		LoadTexture("assets/Tiles/Engine/image_part_026.png"),
		LoadTexture("assets/Tiles/Engine/image_part_027.png"),
		LoadTexture("assets/Tiles/Engine/image_part_028.png"),
		LoadTexture("assets/Tiles/Engine/image_part_029.png"),
		LoadTexture("assets/Tiles/Engine/image_part_030.png"),
		LoadTexture("assets/Tiles/Screen/3/image_part_004.png"),
		LoadTexture("assets/Tiles/Screen/3/image_part_001.png"),
		LoadTexture("assets/Tiles/Screen/3/image_part_002.png"),
		LoadTexture("assets/Tiles/Screen/3/image_part_003.png"),
		LoadTexture("assets/Tiles/Screen/2/image_part_004.png"),
		LoadTexture("assets/Tiles/Screen/2/image_part_001.png"),
		LoadTexture("assets/Tiles/Screen/2/image_part_002.png"),
		LoadTexture("assets/Tiles/Screen/2/image_part_003.png"),
		{0},
		{0},
		{0},
		LoadTexture("assets/Tiles/Screen/1/image_part_008.png"),
		LoadTexture("assets/Tiles/Screen/1/image_part_001.png"),
		LoadTexture("assets/Tiles/Screen/1/image_part_002.png"),
		LoadTexture("assets/Tiles/Screen/1/image_part_003.png"),
		LoadTexture("assets/Tiles/Screen/1/image_part_004.png"),
		LoadTexture("assets/Tiles/Screen/1/image_part_005.png"),
		LoadTexture("assets/Tiles/Screen/1/image_part_006.png"),
		LoadTexture("assets/Tiles/Screen/1/image_part_007.png")
	};

	for (int y = 0; y < MAP_HEIGHT; y++) {
		for (int x = 0; x < MAP_WIDTH; x++) {
			map->sprite[y][x] = (Sprite) {(Rectangle) {MAP_TEXTURE_SCALE*x, MAP_TEXTURE_SCALE*y, MAP_TEXTURE_SCALE, MAP_TEXTURE_SCALE}, array[y][x] >= 2, textures[array[y][x]].id != 0, textures[array[y][x]]};
		}
	}
}

void Map_draw(GameMap * map) {
	for (int y = 0; y < MAP_HEIGHT; y++) 
        for (int x = 0; x < MAP_WIDTH; x++) {
        	if (map->sprite[y][x].hasTexture) {
        		DrawRectangleRec(map->sprite[y][x].rect, LIGHTGRAY);
        		DrawTexture(map->sprite[y][x].texture, map->sprite[y][x].rect.x, map->sprite[y][x].rect.y, WHITE);
        	}
        }
}